# ----------------------------------------------------------------------------
# Playbook: install_minio.yml
# Author: [Mohammad Hosein Soufi Ghorbani] mohamadsoufi700@outlook.com
# Date: 2025-03-09
# Copyright (C) 2025 [Mohammad Hosein Soufi Ghorbani]. All Rights Reserved.
# 
# This playbook is licensed under the MIT License. See the LICENSE file for 
# ----------------------------------------------------------------------------
- hosts: minio_servers
  become: yes
  roles:
    - minio-automate
